# @package _global_

defaults:
  - _self_
  - hydra: default
  - logger: null
  - metrics: null

wandb_run_path: ???
split_to_evaluate: "test"
code_evaluator_id: ???
hidden_test_cases: True
bucketing_id: null

debug: False
silent: False
override: False
complete_override: False
replace_evaluation_output: True

# path to work directory
work_dir: ${hydra:runtime.cwd}

# path to data directory
data_dir: ${work_dir}/data

# path to output directory, created dynamically by hydra
output_dir: ${hydra:runtime.output_dir}

ignore_warnings: False
print_config: True

# Seed used to seed everything in the beginning of the run script and to fix randomness in dataset
seed: 150

# determines the log directory's parent folder
logs_subfolder: metrics_calculation

# experiment name – determines the logging folder's path
run_name: metrics_calculation--${get_wandb_run_name:${wandb_run_path}, ${hydra:job.env_set.WANDB_API_KEY}}
